#!/usr/bin/env groovy

@Library("jenkinsfiles") _


//checkoutSCM.checkout()

//def pipeline = new PipelineGeneral()
//def pipeline = new main.PipelineGeneral()

//def pipeline = new org.cranek.v1.PipelineGeneral()

def pipeline = new src.main.org.cranek.v1.PipelineGeneral()
pipeline.checkout()

