#!/usr/bin/env groovy

@Library("jenkinsfiles") _



def pipeline = new main.groovy.pipelineGeneral()

println(pipeline)

println("sanity check 2")
pipeline.checkout("ip-service1")

println("sanity check 3")

