#!/usr/bin/env groovy

@Library("jenkinsfiles") _


//checkoutSCM.checkout()

//def pipeline = new pipelineGeneral()

def pipeline = new main.PipelineGeneral()
//def pipeline = new main.groovy.org.cranek.v1.PipelineGeneral()
pipeline.checkout()

